# Generated by Django 3.0.3 on 2020-02-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_material',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_material',
            name='name',
            field=models.CharField(choices=[('mask', 'mask'), ('protective_suit', 'protective_suit'), ('goggles', 'goggles'), ('bloodbag', 'bloodbag')], max_length=30),
        ),
    ]
