# Generated by Django 3.0.3 on 2020-02-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_auto_20200223_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital',
            new_name='name',
        ),
    ]
